new Airplanes = mS_INVALID_LISTID,
Boats = mS_INVALID_LISTID,
Bikes = mS_INVALID_LISTID,
Helicopters = mS_INVALID_LISTID,
Industrial = mS_INVALID_LISTID,
Lowriders = mS_INVALID_LISTID,
OffRoad = mS_INVALID_LISTID,
PublicService = mS_INVALID_LISTID,
RCVehicles = mS_INVALID_LISTID,
Saloons = mS_INVALID_LISTID,
SportsVehicles = mS_INVALID_LISTID,
Trailers = mS_INVALID_LISTID,
UniqueVehicles = mS_INVALID_LISTID;

new BlockedVehicle[] = {
    449,
    537,
    538,
    569,
    570,
    590
};