name: Unit Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    name: runner / Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - uses: AGraber/sampctl-action@v1
        with:
          version: '1.10.0'
       
      - run: sampctl p build --forceEnsure
